require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
